// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:string):Promise<main.Preferences>;

export function CanEditFile(arg1:string):Promise<boolean>;

export function CancelAIDocumentReview():Promise<void>;

export function CancelAIRewrite():Promise<void>;

export function CheckForUpdates(arg1:boolean):Promise<main.UpdateInfo>;

export function DetectPandoc():Promise<main.PandocStatus>;

export function DiagnoseAIProvider(arg1:main.AISettingsInput):Promise<main.AIDiagnosticResult>;

export function Dirname(arg1:string):Promise<string>;

export function DiscoverAIModels(arg1:main.AIModelDiscoveryInput):Promise<Array<string>>;

export function DownloadAndApplyUpdate():Promise<void>;

export function ExportDOCX(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportHTML(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ExportPDF(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ExportPlainHTML(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ExportWithPandoc(arg1:main.PandocExportInput):Promise<string>;

export function GetAIProviderSettings(arg1:string):Promise<main.AISettings>;

export function GetAISettings():Promise<main.AISettings>;

export function GetExportSettings():Promise<main.ExportSettings>;

export function GetFeedbackSystemInfo():Promise<main.FeedbackSystemInfo>;

export function GetImageUploadSettings():Promise<main.ImageUploadSettings>;

export function GetInitialFile():Promise<main.Document>;

export function GetPreferences():Promise<main.Preferences>;

export function GetStartupMode():Promise<string>;

export function ImportImage(arg1:string,arg2:string):Promise<string>;

export function ListAIModels(arg1:string):Promise<Array<string>>;

export function ListFolder(arg1:string):Promise<main.FolderResult>;

export function LoginPicGoCloud():Promise<main.PicGoCloudStatus>;

export function LogoutPicGoCloud():Promise<main.ImageUploadSettings>;

export function NeedsLanguageSelection():Promise<boolean>;

export function NewFile():Promise<main.Document>;

export function OpenDefaultApps():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile():Promise<main.Document>;

export function OpenFolder():Promise<main.FolderResult>;

export function OpenRecentFile(arg1:string):Promise<main.Document>;

export function OpenReferenceDocument(arg1:string):Promise<main.Document>;

export function Print():Promise<void>;

export function ReadFile(arg1:string):Promise<main.Document>;

export function ReadImageData(arg1:string,arg2:string):Promise<string>;

export function RemoveFavorite(arg1:string):Promise<main.Preferences>;

export function RemoveRecent(arg1:string):Promise<main.Preferences>;

export function ReorderPinnedRecent(arg1:Array<string>):Promise<main.Preferences>;

export function ReportErrorLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RequestQuit():Promise<boolean>;

export function ReviewDocumentWithAI(arg1:main.AIDocumentReviewRequest):Promise<main.AIDocumentReviewResponse>;

export function RewriteWithAI(arg1:main.AIRewriteRequest):Promise<main.AIRewriteResponse>;

export function SaveAs(arg1:string,arg2:string):Promise<main.Document>;

export function SaveExportImage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveExportImagePages(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<string>>;

export function SaveExportImageSlices(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<main.Document>;

export function SavePastedImage(arg1:string,arg2:string):Promise<string>;

export function SelectFeedbackImages():Promise<Array<main.FeedbackImageSelection>>;

export function SelectImage(arg1:string):Promise<string>;

export function SelectPandoc():Promise<main.PandocStatus>;

export function SetAISettings(arg1:main.AISettingsInput):Promise<main.AISettings>;

export function SetDefaultAIProvider(arg1:string,arg2:string):Promise<main.AISettings>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetExportSettings(arg1:main.ExportSettings):Promise<main.ExportSettings>;

export function SetFontFamily(arg1:string):Promise<string>;

export function SetImageUploadSettings(arg1:main.ImageUploadSettingsInput):Promise<main.ImageUploadSettings>;

export function SetLanguage(arg1:string):Promise<string>;

export function SetRecentPinned(arg1:string,arg2:boolean):Promise<main.Preferences>;

export function SetTheme(arg1:boolean):Promise<void>;

export function SetUsageAnalytics(arg1:boolean):Promise<main.Preferences>;

export function ShowInFolder(arg1:string):Promise<void>;

export function SnoozeUpdates(arg1:number):Promise<void>;

export function SubmitFeedback(arg1:main.FeedbackSubmission):Promise<void>;

export function TestAIConnection():Promise<void>;

export function TestAIProviderConnection(arg1:string,arg2:string):Promise<void>;

export function TestPicGo(arg1:main.ImageUploadSettingsInput):Promise<void>;

export function TestPicGoCloud():Promise<main.PicGoCloudStatus>;

export function UploadImageToPicGo(arg1:string,arg2:string):Promise<string>;

export function UploadImageToPicGoCloud(arg1:string,arg2:string):Promise<string>;
