// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function CanEditFile(arg1) {
  return window['go']['main']['App']['CanEditFile'](arg1);
}

export function CancelAIDocumentReview() {
  return window['go']['main']['App']['CancelAIDocumentReview']();
}

export function CancelAIRewrite() {
  return window['go']['main']['App']['CancelAIRewrite']();
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function DetectPandoc() {
  return window['go']['main']['App']['DetectPandoc']();
}

export function DiagnoseAIProvider(arg1) {
  return window['go']['main']['App']['DiagnoseAIProvider'](arg1);
}

export function Dirname(arg1) {
  return window['go']['main']['App']['Dirname'](arg1);
}

export function DiscoverAIModels(arg1) {
  return window['go']['main']['App']['DiscoverAIModels'](arg1);
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function ExportDOCX(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDOCX'](arg1, arg2, arg3);
}

export function ExportHTML(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportHTML'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportPDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportPlainHTML(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportPlainHTML'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportWithPandoc(arg1) {
  return window['go']['main']['App']['ExportWithPandoc'](arg1);
}

export function GetAIProviderSettings(arg1) {
  return window['go']['main']['App']['GetAIProviderSettings'](arg1);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetExportSettings() {
  return window['go']['main']['App']['GetExportSettings']();
}

export function GetFeedbackSystemInfo() {
  return window['go']['main']['App']['GetFeedbackSystemInfo']();
}

export function GetImageUploadSettings() {
  return window['go']['main']['App']['GetImageUploadSettings']();
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetStartupMode() {
  return window['go']['main']['App']['GetStartupMode']();
}

export function ImportImage(arg1, arg2) {
  return window['go']['main']['App']['ImportImage'](arg1, arg2);
}

export function ListAIModels(arg1) {
  return window['go']['main']['App']['ListAIModels'](arg1);
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function LoginPicGoCloud() {
  return window['go']['main']['App']['LoginPicGoCloud']();
}

export function LogoutPicGoCloud() {
  return window['go']['main']['App']['LogoutPicGoCloud']();
}

export function NeedsLanguageSelection() {
  return window['go']['main']['App']['NeedsLanguageSelection']();
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenDefaultApps() {
  return window['go']['main']['App']['OpenDefaultApps']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenRecentFile(arg1) {
  return window['go']['main']['App']['OpenRecentFile'](arg1);
}

export function OpenReferenceDocument(arg1) {
  return window['go']['main']['App']['OpenReferenceDocument'](arg1);
}

export function Print() {
  return window['go']['main']['App']['Print']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadImageData(arg1, arg2) {
  return window['go']['main']['App']['ReadImageData'](arg1, arg2);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RemoveRecent(arg1) {
  return window['go']['main']['App']['RemoveRecent'](arg1);
}

export function ReorderPinnedRecent(arg1) {
  return window['go']['main']['App']['ReorderPinnedRecent'](arg1);
}

export function ReportErrorLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReportErrorLog'](arg1, arg2, arg3);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function ReviewDocumentWithAI(arg1) {
  return window['go']['main']['App']['ReviewDocumentWithAI'](arg1);
}

export function RewriteWithAI(arg1) {
  return window['go']['main']['App']['RewriteWithAI'](arg1);
}

export function SaveAs(arg1, arg2) {
  return window['go']['main']['App']['SaveAs'](arg1, arg2);
}

export function SaveExportImage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveExportImage'](arg1, arg2, arg3, arg4);
}

export function SaveExportImagePages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveExportImagePages'](arg1, arg2, arg3, arg4);
}

export function SaveExportImageSlices(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveExportImageSlices'](arg1, arg2, arg3, arg4);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SavePastedImage(arg1, arg2) {
  return window['go']['main']['App']['SavePastedImage'](arg1, arg2);
}

export function SelectFeedbackImages() {
  return window['go']['main']['App']['SelectFeedbackImages']();
}

export function SelectImage(arg1) {
  return window['go']['main']['App']['SelectImage'](arg1);
}

export function SelectPandoc() {
  return window['go']['main']['App']['SelectPandoc']();
}

export function SetAISettings(arg1) {
  return window['go']['main']['App']['SetAISettings'](arg1);
}

export function SetDefaultAIProvider(arg1, arg2) {
  return window['go']['main']['App']['SetDefaultAIProvider'](arg1, arg2);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetExportSettings(arg1) {
  return window['go']['main']['App']['SetExportSettings'](arg1);
}

export function SetFontFamily(arg1) {
  return window['go']['main']['App']['SetFontFamily'](arg1);
}

export function SetImageUploadSettings(arg1) {
  return window['go']['main']['App']['SetImageUploadSettings'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetRecentPinned(arg1, arg2) {
  return window['go']['main']['App']['SetRecentPinned'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetUsageAnalytics(arg1) {
  return window['go']['main']['App']['SetUsageAnalytics'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function SnoozeUpdates(arg1) {
  return window['go']['main']['App']['SnoozeUpdates'](arg1);
}

export function SubmitFeedback(arg1) {
  return window['go']['main']['App']['SubmitFeedback'](arg1);
}

export function TestAIConnection() {
  return window['go']['main']['App']['TestAIConnection']();
}

export function TestAIProviderConnection(arg1, arg2) {
  return window['go']['main']['App']['TestAIProviderConnection'](arg1, arg2);
}

export function TestPicGo(arg1) {
  return window['go']['main']['App']['TestPicGo'](arg1);
}

export function TestPicGoCloud() {
  return window['go']['main']['App']['TestPicGoCloud']();
}

export function UploadImageToPicGo(arg1, arg2) {
  return window['go']['main']['App']['UploadImageToPicGo'](arg1, arg2);
}

export function UploadImageToPicGoCloud(arg1, arg2) {
  return window['go']['main']['App']['UploadImageToPicGoCloud'](arg1, arg2);
}
